version: '3'

services:
  app: 
    build:
      context: . #todos los archivos en la carpeta actual
      dockerfile: App.Dockerfile
   
    environment:
      -FLAS_ENV: development 
      -FLASK_APP: flaskr  
    
    volumes:       
      - database:/usr/src/app/instance

    expose:
      - "8080"

    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "8080:80" 
    
    networks:
      - app-network
    
    depends_on:
      - app

volumes:
  database:

networks:
  app-network:
    driver: bridge


